{"uuid": "11793e66-98b1-4d3a-84bd-fa52307d9e74", "counter": 57, "stdout": "\u001b[0;34m<192.168.122.34> Failed to connect to the host via ssh: debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\u001b[0m\r\n\u001b[0;34mdebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\u001b[0m\r\n\u001b[0;34mdebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\\" -o User=\\\\\"mcmxcviii\\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\\" 192.168.122.34 \"/bin/sh -c \\\\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\\\'\"\r\u001b[0m\r\n\u001b[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config\r\u001b[0m\r\n\u001b[0;34mdebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\u001b[0m\r\n\u001b[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\u001b[0m\r\n\u001b[0;34mdebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\u001b[0m\r\n\u001b[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\u001b[0m\r\n\u001b[0;34mdebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\u001b[0m\r\n\u001b[0;34mdebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\u001b[0m\r\n\u001b[0;34mdebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\u001b[0m\r\n\u001b[0;34mdebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/de121b807f'\r\u001b[0m\r\n\u001b[0;34mdebug2: fd 3 setting O_NONBLOCK\r\u001b[0m\r\n\u001b[0;34mdebug2: mux_client_hello_exchange: master version 4\r\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_request_session: entering\r\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_request_alive: entering\r\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_request_alive: done pid = 64140\r\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_request_session: session request sent\r\u001b[0m\r\n\u001b[0;34mdebug1: mux_client_request_session: master session id: 2\r\u001b[0m\r\n\u001b[0;34m/bin/sh: \u0441\u0442\u0440\u043e\u043a\u0430 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: \u041d\u0435\u0442 \u0442\u0430\u043a\u043e\u0433\u043e \u0444\u0430\u0439\u043b\u0430 \u0438\u043b\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\u001b[0m\r\n\u001b[0;34mdebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\u001b[0m\r\n\u001b[0;34mdebug2: Received exit status from master 127\u001b[0m", "start_line": 158, "end_line": 181, "runner_ident": "1cda0fff-0e44-43b9-98c6-ff53b2a63e69", "event": "verbose", "pid": 64346, "created": "2025-04-15T16:00:17.496508+00:00", "parent_uuid": "38d57ae8-a7f1-02ac-9ad4-000000000022", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "490cd1d1-af79-4906-a7af-1f10259e7cdd", "play": "Select the least loaded server", "play_uuid": "38d57ae8-a7f1-02ac-9ad4-000000000007", "play_pattern": "localhost", "task": "Gathering Facts", "task_uuid": "38d57ae8-a7f1-02ac-9ad4-000000000022", "task_action": "gather_facts", "resolved_action": "ansible.builtin.gather_facts", "task_args": "", "task_path": "/home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:20", "uuid": "11793e66-98b1-4d3a-84bd-fa52307d9e74"}}