[0;34mansible-playbook [core 2.18.4][0m
[0;34m  config file = /home/mcmxcviii/Documents/gh1/pg_install/ansible.cfg[0m
[0;34m  configured module search path = ['/home/mcmxcviii/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'][0m
[0;34m  ansible python module location = /home/mcmxcviii/Documents/gh1/pg_install/venv/lib/python3.13/site-packages/ansible[0m
[0;34m  ansible collection location = /home/mcmxcviii/.ansible/collections:/usr/share/ansible/collections[0m
[0;34m  executable location = /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/ansible-playbook[0m
[0;34m  python version = 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] (/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python)[0m
[0;34m  jinja version = 3.1.6[0m
[0;34m  libyaml = True[0m
[0;34mUsing /home/mcmxcviii/Documents/gh1/pg_install/ansible.cfg as config file[0m
[0;34mhost_list declined parsing /home/mcmxcviii/Documents/gh1/pg_install/inventory/hosts as it did not pass its verify_file() method[0m
[0;34mscript declined parsing /home/mcmxcviii/Documents/gh1/pg_install/inventory/hosts as it did not pass its verify_file() method[0m
[0;34mauto declined parsing /home/mcmxcviii/Documents/gh1/pg_install/inventory/hosts as it did not pass its verify_file() method[0m
[0;34mParsed /home/mcmxcviii/Documents/gh1/pg_install/inventory/hosts inventory source with ini plugin[0m
[0;34mSkipping callback 'awx_display', as we already have a stdout callback.[0m
[0;34mSkipping callback 'default', as we already have a stdout callback.[0m
[0;34mSkipping callback 'minimal', as we already have a stdout callback.[0m
[0;34mSkipping callback 'oneline', as we already have a stdout callback.[0m
 ________________________
< PLAYBOOK: playbook.yml >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[0;34m2 plays in playbook.yml[0m
 __________________________
< PLAY [Check server load] >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 ____________________________________
< TASK [Get system load information] >
 ------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[1;30mtask path: /home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:8[0m
[0;34m<inventory.ini> Attempting python interpreter discovery[0m
[0;34m<192.168.122.34> ESTABLISH SSH CONNECTION FOR USER: mcmxcviii[0m
[0;34m<192.168.122.34> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/mcmxcviii/.ssh/id_ed25519"' -o 'User="mcmxcviii"' -o ConnectTimeout=10 -o 'ControlPath="/home/mcmxcviii/.ansible/cp/de121b807f"' 192.168.122.34 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'python3.13'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.12'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.11'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.10'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.9'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.8'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''[0m
[0;34m<192.168.122.34> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3.11\n/usr/bin/python3.9\n/usr/bin/python3\n/usr/bin/python3\nENDFOUND\n', b'debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\" -o User=\\\\"mcmxcviii\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\" 192.168.122.34 "/bin/sh -c \\\\\'echo PLATFORM; uname; echo FOUND; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.13\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.12\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.11\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.10\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.9\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3.8\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'/usr/bin/python3\\\\\'\\\\"\\\\\'\\\\"\\\\\'; command -v \\\\\'\\\\"\\\\\'\\\\"\\\\\'python3\\\\\'\\\\"\\\\\'\\\\"\\\\\'; echo ENDFOUND && sleep 0\\\\\'"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/mcmxcviii/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/mcmxcviii/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master at \'/home/mcmxcviii/.ansible/cp/de121b807f\'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')[0m
[0;34m<192.168.122.34> ESTABLISH SSH CONNECTION FOR USER: mcmxcviii[0m
[0;34m<192.168.122.34> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/mcmxcviii/.ssh/id_ed25519"' -o 'User="mcmxcviii"' -o ConnectTimeout=10 -o 'ControlPath="/home/mcmxcviii/.ansible/cp/de121b807f"' 192.168.122.34 '/bin/sh -c '"'"'/usr/bin/python3.11 && sleep 0'"'"''[0m
[0;34m<192.168.122.34> (0, b'{"platform_dist_result": [], "osrelease_content": "NAME=\\"AlmaLinux\\"\\nVERSION=\\"9.5 (Teal Serval)\\"\\nID=\\"almalinux\\"\\nID_LIKE=\\"rhel centos fedora\\"\\nVERSION_ID=\\"9.5\\"\\nPLATFORM_ID=\\"platform:el9\\"\\nPRETTY_NAME=\\"AlmaLinux 9.5 (Teal Serval)\\"\\nANSI_COLOR=\\"0;34\\"\\nLOGO=\\"fedora-logo-icon\\"\\nCPE_NAME=\\"cpe:/o:almalinux:almalinux:9::baseos\\"\\nHOME_URL=\\"https://almalinux.org/\\"\\nDOCUMENTATION_URL=\\"https://wiki.almalinux.org/\\"\\nBUG_REPORT_URL=\\"https://bugs.almalinux.org/\\"\\n\\nALMALINUX_MANTISBT_PROJECT=\\"AlmaLinux-9\\"\\nALMALINUX_MANTISBT_PROJECT_VERSION=\\"9.5\\"\\nREDHAT_SUPPORT_PRODUCT=\\"AlmaLinux\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"9.5\\"\\nSUPPORT_END=2032-06-01\\n"}\n', b'debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\" -o User=\\\\"mcmxcviii\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\" 192.168.122.34 "/bin/sh -c \\\\\'/usr/bin/python3.11 && sleep 0\\\\\'"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/mcmxcviii/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/mcmxcviii/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master at \'/home/mcmxcviii/.ansible/cp/de121b807f\'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')[0m
[0;34m<inventory.ini> Python interpreter discovery fallback (unsupported Linux distribution: almalinux)[0m
[0;34mUsing module file /home/mcmxcviii/Documents/gh1/pg_install/venv/lib/python3.13/site-packages/ansible/modules/command.py[0m
[0;34mPipelining is enabled.[0m
[0;34m<192.168.122.34> ESTABLISH SSH CONNECTION FOR USER: mcmxcviii[0m
[0;34m<192.168.122.34> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/mcmxcviii/.ssh/id_ed25519"' -o 'User="mcmxcviii"' -o ConnectTimeout=10 -o 'ControlPath="/home/mcmxcviii/.ansible/cp/de121b807f"' 192.168.122.34 '/bin/sh -c '"'"'/usr/bin/python3.11 && sleep 0'"'"''[0m
[0;34m<192.168.122.34> (0, b'\n{"changed": true, "stdout": " 19:01:44 up  4:09,  2 users,  load average: 0,08, 0,02, 0,01", "stderr": "", "rc": 0, "cmd": ["uptime"], "start": "2025-04-15 19:01:44.854445", "end": "2025-04-15 19:01:44.857210", "delta": "0:00:00.002765", "msg": "", "invocation": {"module_args": {"_raw_params": "uptime", "_uses_shell": false, "expand_argument_vars": true, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\n', b'debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\" -o User=\\\\"mcmxcviii\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\" 192.168.122.34 "/bin/sh -c \\\\\'/usr/bin/python3.11 && sleep 0\\\\\'"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/mcmxcviii/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/mcmxcviii/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master at \'/home/mcmxcviii/.ansible/cp/de121b807f\'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')[0m
[1;35m[WARNING]: Platform linux on host inventory.ini is using the discovered Python[0m
[1;35minterpreter at /usr/bin/python3.11, but future installation of another Python[0m
[1;35minterpreter could change the meaning of that path. See[0m
[1;35mhttps://docs.ansible.com/ansible-[0m
[1;35mcore/2.18/reference_appendices/interpreter_discovery.html for more information.[0m
[0;33mchanged: [inventory.ini] => {[0m
[0;33m    "ansible_facts": {[0m
[0;33m        "discovered_interpreter_python": "/usr/bin/python3.11"[0m
[0;33m    },[0m
[0;33m    "changed": true,[0m
[0;33m    "cmd": [[0m
[0;33m        "uptime"[0m
[0;33m    ],[0m
[0;33m    "delta": "0:00:00.002765",[0m
[0;33m    "end": "2025-04-15 19:01:44.857210",[0m
[0;33m    "invocation": {[0m
[0;33m        "module_args": {[0m
[0;33m            "_raw_params": "uptime",[0m
[0;33m            "_uses_shell": false,[0m
[0;33m            "argv": null,[0m
[0;33m            "chdir": null,[0m
[0;33m            "creates": null,[0m
[0;33m            "executable": null,[0m
[0;33m            "expand_argument_vars": true,[0m
[0;33m            "removes": null,[0m
[0;33m            "stdin": null,[0m
[0;33m            "stdin_add_newline": true,[0m
[0;33m            "strip_empty_ends": true[0m
[0;33m        }[0m
[0;33m    },[0m
[0;33m    "msg": "",[0m
[0;33m    "rc": 0,[0m
[0;33m    "start": "2025-04-15 19:01:44.854445",[0m
[0;33m    "stderr": "",[0m
[0;33m    "stderr_lines": [],[0m
[0;33m    "stdout": " 19:01:44 up  4:09,  2 users,  load average: 0,08, 0,02, 0,01",[0m
[0;33m    "stdout_lines": [[0m
[0;33m        " 19:01:44 up  4:09,  2 users,  load average: 0,08, 0,02, 0,01"[0m
[0;33m    ][0m
[0;33m}[0m
 _____________________________
< TASK [Extract average load] >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[1;30mtask path: /home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:12[0m
[0;32mok: [inventory.ini] => {[0m
[0;32m    "ansible_facts": {[0m
[0;32m        "load_average": "0.0"[0m
[0;32m    },[0m
[0;32m    "changed": false[0m
[0;32m}[0m
 ______________________________
< TASK [Save load information] >
 ------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[1;30mtask path: /home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:16[0m
[0;32mok: [inventory.ini] => {[0m
[0;32m    "ansible_facts": {[0m
[0;32m        "server_loads": {[0m
[0;32m            "inventory.ini": "0.0"[0m
[0;32m        }[0m
[0;32m    },[0m
[0;32m    "changed": false[0m
[0;32m}[0m
 _______________________________________
< PLAY [Select the least loaded server] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[1;30mtask path: /home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:20[0m
[0;34mUsing module file /home/mcmxcviii/Documents/gh1/pg_install/venv/lib/python3.13/site-packages/ansible/modules/setup.py[0m
[0;34mPipelining is enabled.[0m
[0;34m<192.168.122.34> ESTABLISH SSH CONNECTION FOR USER: mcmxcviii[0m
[0;34m<192.168.122.34> SSH: EXEC sshpass -d13 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/mcmxcviii/.ssh/id_ed25519"' -o 'User="mcmxcviii"' -o ConnectTimeout=10 -o 'ControlPath="/home/mcmxcviii/.ansible/cp/de121b807f"' 192.168.122.34 '/bin/sh -c '"'"'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0'"'"''[0m
[0;34m<192.168.122.34> (127, b'', b'debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\" -o User=\\\\"mcmxcviii\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\" 192.168.122.34 "/bin/sh -c \\\\\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\\\\'"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/home/mcmxcviii/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/home/mcmxcviii/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master at \'/home/mcmxcviii/.ansible/cp/de121b807f\'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n/bin/sh: \xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xba\xd0\xb0 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: \xd0\x9d\xd0\xb5\xd1\x82 \xd1\x82\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb3\xd0\xbe \xd1\x84\xd0\xb0\xd0\xb9\xd0\xbb\xd0\xb0 \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xba\xd0\xb0\xd1\x82\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb0\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 127\r\n')[0m
[0;34m<192.168.122.34> Failed to connect to the host via ssh: debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025[0m
[0;34mdebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64[0m
[0;34mdebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\"/home/mcmxcviii/.ssh/id_ed25519\\" -o User=\\"mcmxcviii\\" -o ConnectTimeout=10 -o ControlPath=\\"/home/mcmxcviii/.ansible/cp/de121b807f\\" 192.168.122.34 "/bin/sh -c \\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\'"[0m
[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config[0m
[0;34mdebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0[0m
[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf[0m
[0;34mdebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0[0m
[0;34mdebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf[0m
[0;34mdebug2: resolve_canonicalize: hostname 192.168.122.34 is address[0m
[0;34mdebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'[0m
[0;34mdebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'[0m
[0;34mdebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/de121b807f'[0m
[0;34mdebug2: fd 3 setting O_NONBLOCK[0m
[0;34mdebug2: mux_client_hello_exchange: master version 4[0m
[0;34mdebug3: mux_client_forwards: request forwardings: 0 local, 0 remote[0m
[0;34mdebug3: mux_client_request_session: entering[0m
[0;34mdebug3: mux_client_request_alive: entering[0m
[0;34mdebug3: mux_client_request_alive: done pid = 64553[0m
[0;34mdebug3: mux_client_request_session: session request sent[0m
[0;34mdebug1: mux_client_request_session: master session id: 2[0m
[0;34m/bin/sh: строка 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: Нет такого файла или каталога[0m
[0;34mdebug3: mux_client_read_packet_timeout: read header failed: Broken pipe[0m
[0;34mdebug2: Received exit status from master 127[0m
[0;31mfatal: [localhost]: FAILED! => {[0m
[0;31m    "ansible_facts": {},[0m
[0;31m    "changed": false,[0m
[0;31m    "failed_modules": {[0m
[0;31m        "ansible.legacy.setup": {[0m
[0;31m            "failed": true,[0m
[0;31m            "module_stderr": "debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\\" -o User=\\\\\"mcmxcviii\\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\\" 192.168.122.34 \"/bin/sh -c \\\\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\\\'\"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/de121b807f'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n/bin/sh: строка 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: Нет такого файла или каталога\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 127\r\n",[0m
[0;31m            "module_stdout": "",[0m
[0;31m            "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",[0m
[0;31m            "rc": 127[0m
[0;31m        }[0m
[0;31m    },[0m
[0;31m    "msg": "The following modules failed to execute: ansible.legacy.setup\n"[0m
[0;31m}[0m
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[0;33minventory.ini[0m              : [0;32mok=3   [0m [0;33mchanged=1   [0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
[0;31mlocalhost[0m                  : ok=0    changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0   
