{"uuid": "708e52d7-5605-4f0d-aedd-2a8a56867e42", "counter": 58, "stdout": "\u001b[0;31mfatal: [localhost]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"ansible_facts\": {},\u001b[0m\r\n\u001b[0;31m    \"changed\": false,\u001b[0m\r\n\u001b[0;31m    \"failed_modules\": {\u001b[0m\r\n\u001b[0;31m        \"ansible.legacy.setup\": {\u001b[0m\r\n\u001b[0;31m            \"failed\": true,\u001b[0m\r\n\u001b[0;31m            \"module_stderr\": \"debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\\r\\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\\r\\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\\\\\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\\\\\\\\" -o User=\\\\\\\\\\\"mcmxcviii\\\\\\\\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\\\\\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\\\\\\\\" 192.168.122.34 \\\"/bin/sh -c \\\\\\\\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\\\\\\\'\\\"\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\\r\\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\\r\\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/de121b807f'\\r\\ndebug2: fd 3 setting O_NONBLOCK\\r\\ndebug2: mux_client_hello_exchange: master version 4\\r\\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\\r\\ndebug3: mux_client_request_session: entering\\r\\ndebug3: mux_client_request_alive: entering\\r\\ndebug3: mux_client_request_alive: done pid = 64553\\r\\ndebug3: mux_client_request_session: session request sent\\r\\ndebug1: mux_client_request_session: master session id: 2\\r\\n/bin/sh: \u0441\u0442\u0440\u043e\u043a\u0430 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: \u041d\u0435\u0442 \u0442\u0430\u043a\u043e\u0433\u043e \u0444\u0430\u0439\u043b\u0430 \u0438\u043b\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\\r\\ndebug2: Received exit status from master 127\\r\\n\",\u001b[0m\r\n\u001b[0;31m            \"module_stdout\": \"\",\u001b[0m\r\n\u001b[0;31m            \"msg\": \"MODULE FAILURE: No start of json char found\\nSee stdout/stderr for the exact error\",\u001b[0m\r\n\u001b[0;31m            \"rc\": 127\u001b[0m\r\n\u001b[0;31m        }\u001b[0m\r\n\u001b[0;31m    },\u001b[0m\r\n\u001b[0;31m    \"msg\": \"The following modules failed to execute: ansible.legacy.setup\\n\"\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 181, "end_line": 195, "runner_ident": "45f292bb-0d54-490b-a527-f099cbcf42e8", "event": "runner_on_failed", "pid": 64659, "created": "2025-04-15T16:01:45.300703+00:00", "parent_uuid": "38d57ae8-a7f1-9fbd-cecd-000000000022", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "838300f4-3351-4a0c-a4d1-8e2b908b9cdc", "play": "Select the least loaded server", "play_uuid": "38d57ae8-a7f1-9fbd-cecd-000000000007", "play_pattern": "localhost", "task": "Gathering Facts", "task_uuid": "38d57ae8-a7f1-9fbd-cecd-000000000022", "task_action": "gather_facts", "resolved_action": "ansible.builtin.gather_facts", "task_args": "", "task_path": "/home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:20", "host": "localhost", "remote_addr": "127.0.0.1", "res": {"ansible_facts": {}, "msg": "The following modules failed to execute: ansible.legacy.setup\n", "failed_modules": {"ansible.legacy.setup": {"failed": true, "module_stdout": "", "module_stderr": "debug1: OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug3: Running on Linux 6.14.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:47 +0000 x86_64\r\ndebug3: Started with: ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o IdentityFile=\\\\\"/home/mcmxcviii/.ssh/id_ed25519\\\\\" -o User=\\\\\"mcmxcviii\\\\\" -o ConnectTimeout=10 -o ControlPath=\\\\\"/home/mcmxcviii/.ansible/cp/de121b807f\\\\\" 192.168.122.34 \"/bin/sh -c \\\\'/home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python && sleep 0\\\\'\"\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug2: resolve_canonicalize: hostname 192.168.122.34 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/de121b807f'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 64553\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n/bin/sh: \u0441\u0442\u0440\u043e\u043a\u0430 1: /home/mcmxcviii/Documents/gh1/pg_install/venv/bin/python: \u041d\u0435\u0442 \u0442\u0430\u043a\u043e\u0433\u043e \u0444\u0430\u0439\u043b\u0430 \u0438\u043b\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 127\r\n", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 127}}, "_ansible_verbose_override": true, "_ansible_no_log": false, "changed": false}, "start": "2025-04-15T16:01:45.029157+00:00", "end": "2025-04-15T16:01:45.300597+00:00", "duration": 0.27144, "ignore_errors": null, "event_loop": null, "uuid": "708e52d7-5605-4f0d-aedd-2a8a56867e42"}}